var app = new Vue({
  el: '#app',
  data: {
    name: 'X-ray',
    nouns: [
        'zero',
        'acceleration',
        'Aerolite',
        'Airglow',
        'albedo',
        'Apastron',
        'Aphelion',
        'Apogee',
        'Asteroid',
        'Atmosphere',
        'Atom',
        'Aurora',
        'star',
        'Black Hole',
        'Bolide',
        'Chromosphere',
        'Cluster',
        'comet',
        'Corona',
        'ray',
        'X-ray',
        'Eclipse',
        'Ecosphere',
        'Electron',
        'Exosphere',
        'Galaxy',
        'Planet',
        'Light Year',
        'Meteor',
        'Meteorite',
        'Nebula',
        'Neutrino',
        'Nova',
        'Occultation',
        'Parallax',
        'Periastron',
        'Perigee',
        'Perihelion',
        'Photosphere',
        'Quasar',
        'Satellite',
        'Scintillation',
        'Solstice',
        'Spicules',
        'Supernova',
        'Terminator',
        'Troposphere',
        'nucleus',
        'sky',
        'matter',
        'Fireball',
        'Hadron',
    ],
    adjectives: [
        'absolute',
        'Annular',
        'Celestial',
        'Circumpolar',
        'cosmic',
        'Solar',
        'Geocentric',
        // 'Gibbous',
        'inferior',
        'sidereal',
        'Superior',
        'dark',
        'Lunar',

    ],
  }
})
